[project]
name = "bushido"
version = "0.1.0"
description = "Track Trainings and Study Time"
authors = [
    {name = "Noe Javet", email = "np.javet@gmail.com"}
]
license = {text = "GPL-3"}
readme = "README.md"
requires-python = ">=3.13,<4.0.0"
dependencies = [
    "sqlalchemy (>=2.0.43,<3.0.0)",
    "fastapi[standard] (>=0.118.0,<0.119.0)",
    "textual[syntax] (>=6.2.1,<7.0.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "polars (>=1.34.0,<2.0.0)",
    "xarray (>=2025.9.1,<2026.0.0)",
    "platformdirs (>=4.4.0,<5.0.0)",
    "textual-image (>=0.8.4,<0.9.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "bushido"
packages = [{ include = "bushido", from = "src"}]

[tool.poetry.scripts]
bushido = "bushido.__main__:main"

[tool.poetry.group.test.dependencies]
ruff = "^0.13.3"
coverage = "^7.10.7"
mypy = "^1.18.2"
pytest = "^8.4.2"
pytest-mock = "^3.15.1"
poethepoet = "^0.37.0"


[tool.poetry.group.dev.dependencies]
ipython = "^9.6.0"

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
python_version = "3.13"
packages = ["bushido", "tests"]
strict = true
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
no_implicit_optional = true
disallow_untyped_defs = true
disallow_any_generics = true
strict_equality = true
pretty = true
plugins = [
    "sqlalchemy.ext.mypy.plugin",
    "pydantic.mypy"
]

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false

[tool.poe.tasks]
install = "poetry install --no-root"
lint = "ruff check --fix ."
fmt = "ruff format ."
typecheck = "mypy --strict src"
test = "pytest -q2"
check = ["lint", "typecheck", "test"]


